#pragma once

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 1

#define TAPPING_TERM 110
#define COMBO_TERM 27
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define QUICK_TAP_TERM_PER_KEY

#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define RETRO_TAPPING_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY
#define COMBO_SHOULD_TRIGGER

#define ENABLE_COMPILE_KEYCODE

#define NUM_ENCODERS 1
#define NUM_DIRECTIONS 2
#define ENCODER_A_PINS  { GP0 }
#define ENCODER_B_PINS  { GP10 }
#define ENCODER_RESOLUTION 2