#pragma once

#define TAPPING_TERM 120
#define COMBO_TERM 27
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define QUICK_TAP_TERM_PER_KEY

#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define RETRO_TAPPING_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY
#define COMBO_SHOULD_TRIGGER

#define ENABLE_COMPILE_KEYCODE

#define NUM_ENCODERS 1
#define ENCODERS_PAD_A  { GP2 }
#define ENCODERS_PAD_B  { GP3 }
#define ENCODER_RESOLUTION 2